webapp/config/routes.rb
Rails.application.routes.draw do

  get 'pages/home' => 'pages#home', as: 'home'
  get 'pages/remonte' => 'pages#remonte', as: 'remonte'
  get 'pages/reseaux' => 'pages#reseaux', as: 'reseaux'

  root 'pages#home'

  get 'issues/get_more_info/:id' => 'issues#get_more_info', as: 'get_more_info'
  resources :issues

  post 'ajax/set_ip_loc' => 'ajax#set_ip_loc', as: 'set_ip_loc'

end

webapp/app/models/issue.rb
class Issue < ActiveRecord::Base

  mount_uploader :picture, PictureUploader

end

webapp/app/models/user.rb
class User < ActiveRecord::Base

end

webapp/app/controllers/ajax_controller.rb
class AjaxController < ApplicationController

 protect_from_forgery except: :set_ip_loc

  def set_ip_loc
    json = request.raw_post
    data = JSON.parse(json)
    # data = JSON.parse(data)
    data = data.to_json
    data = JSON.parse(data)
    session[:ip] = data["ip"]
    session[:lat] = data["lat"]
    session[:pos] = data["pos"]
    render nothing: true
  end

end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

webapp/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :prevent_loc_ip, only: [:new]

  def new
    @issue =  Issue.new
    render layout: false
  end

  def create
    issue = Issue.new(issue_params)
    # issue = Issue.create(issue_params)
    issue.ip = session[:ip]
    issue.latitude = session[:lat]
    issue.longitude = session[:pos]
    if issue.save
      redirect_to get_more_info_path(issue)
    else
      flash[:error] = "Le problème n'a pas pu être pris en compte"
      redirect_to root_path
    end
    # redirect_to root_path
  end

  def get_more_info
    @issue = Issue.find(params[:id].to_i)
    render layout: false
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def update
    issue = Issue.find(params[:id].to_i)
    if params[:more] == 1.to_s
      if issue.update_attributes(up_from_more)
        flash[:notice] = "Merci les informations supplémentaires ont bien été reçues"
        redirect_to get_more_info_path(issue)
      else
        flash[:warning] = "Les informations supplémentaires n'ont pas pu être reçues"
        redirect_to get_more_info_path(issue)
      end
    end
  end

  def index
    @issues = Issue.all.sort_by(&:issue_level).reverse
    @title = "Dashboard"
  end

  private

  def issue_params
    params.require(:issue).permit(:typeofperson, :nbr_victims, :issue_level)
  end

  def up_from_more
    params.require(:issue).permit(:phone, :picture, :name, :last_name)
  end

  def prevent_loc_ip
    if session[:ip].nil? || session[:lat].nil? || session[:pos].nil?
      redirect_to root_path
    end
  end

end

webapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def welcome
    @title = "Welcome"
  end

  def dashboard
  end

  def remonte
    @title = "Signalements"
    @issues = Issue.all.sort_by(&:issue_level)
  end

  def reseaux
    @title = "Réseaux-Sociaux"
  end
end

webapp/app/helpers/ajax_helper.rb
module AjaxHelper
end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/helpers/issues_helper.rb
module IssuesHelper
end

webapp/app/helpers/pages_helper.rb
module PagesHelper
end

webapp/app/views/issues/get_more_info.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html">
  <meta charset="UTF-8">
  <title>SIGNALEMENT D'UNE URGENCE</title>
    <!-- <link rel="stylesheet" href="test.css"> -->
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <%= stylesheet_link_tag    'form_issue', media: 'all' %>
    <meta name="viewport" content="width=device-width, user-scalable=yes" />
    <%= csrf_meta_tags %>
 </head>
<body>
<div id = "header">
    <a>
        <object data="/images/gendarmerie_logo.svg" type="image/svg+xml" style="height:30px"></object>
    </a>
    SIGNALEMENT D'UNE URGENCE
</div>

<!-- <div class="container"> -->
<div class="alert alert-success">
  <center>
    <p style="text-align:center;">
      Votre signalement a été pris en compte <br/>
      _<br/>
      Les secours sont alertés
    </p>
</center>
</div>

<section class="round">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
</section>

<div class ="container" style="background:#DCDCDC;">

<%= form_for(@issue) do |f| %>
<input type="hidden" value="1" name="more">
<input id="typers" type="hidden" name="issue[typeofperson]" value="0">
    <div class = "row-g">
      <div class = "my-header" style="margin-top:10px">
        <div class="my-font-header">Je rajoute mon numéro de téléphone</div>
      </div>
      <div class="col-md-12">
        <%= f.telephone_field :phone, class: "test" %>
      </div>
    </div>

    <div class = "row-g">
      <div class = "my-header" style="margin-top:10px">
        <div class="my-font-header">Je rajoute mon Prénom</div>
      </div>
      <div class="col-md-12">
        <%= f.text_field :name, class: "test" %>
      </div>
    </div>

    <div class = "row-g">
      <div class = "my-header" style="margin-top:10px">
        <div class="my-font-header">Je rajoute mon nom de famille</div>
      </div>
      <div class="col-md-12">
        <%= f.text_field :last_name, class: "test" %>
      </div>
    </div>

    <div class = "row-g">
      <div class = "my-header" style="margin-top:10px">
        <div class="my-font-header">J'envoie une photo</div>
      </div>
      <div class="col-md-12">
        <%= f.file_field :picture, class: "test" %>
      </div>
    </div>

    <div class="actions">
        <button name="commit" type="submit" class="btn btn-primary btn-block" value="SIGNALER" style="width:100%; height:100px">
          <span class="glyphicon glyphicon-upload"></span> SIGNALER
        </button>
    </div>
  <% end %>
</div>
<div id = "header" style="text-align:center">
    <a>
        <object data="gendarmerie_logo.svg" type="image/svg+xml" style="height:30px"></object>
    </a>
    Vous êtes en contact avec les services d'urgence</br>
    ip : <%= session[:ip] %>
    localisation : <%= session[:lat] %> / <%= session[:pos] %>
</div>

<script>
$( document ).ready(function() {
  $('#vict').click(function(){
    $("#typers").val('1');
  });

  $('#tem').click(function(){
    $("#typers").val('0');
  });
});
</script>
</body>
</html>

webapp/app/views/issues/index.html.erb
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag    'leaflet.awesome-markers', media: 'all'%>

    <%= stylesheet_link_tag    'http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css', media: 'all'%>

     <%= stylesheet_link_tag    'stopcambriolage_catastrophe', media: 'all'%>

    <link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


<style>
      #sortable-10, #sortable-11 { list-style-type: none;
         margin: 0; padding: 0; width: 100%; }
      #sortable-10 li, #sortable-11 li { margin: 0 3px 3px 3px;
         padding: 1.0em;
          }
      .highlight {
         border: 1px solid #000000;
         font-weight: bold;
         font-size: 45px;
         background-color: #cedc98;
      }
      .default {
         background: #cedc98;
         border: 1px solid #DDDDDD;
         color: #333333;
        width: 100%;
        border-radius: 5px;
         }
      .wrap{
         display: table-row-group;
         }
      .wrap1{
         float:left;
         width: 100%;
      }
   </style>

<body>

    <!--
    ---- NAVIGATION BAR
    --->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/issues">
                  <%= image_tag("gendarmerie_logo.svg", height: '30') %>
                </a>
            </div>
            <!-- /.navbar-header -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="/issues">VSU</a>
                    </li>
                    <li>
                        <a href="/pages/remonte">Signalements</a>
                    </li>
                    <!--<li>
                        <a href="/pages/info">Statistiques</a>
                    </li>-->
                    <li>
                        <a href="/pages/reseaux">Réseaux Sociaux</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        sicard_f&nbsp;
                        <i class="fa fa-chevron-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-refresh" style="margin-right:10px"></i>Mode Catastrophe</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-sign-out" style="margin-right:8px"></i>Déconnexion</a>
                        </li>
                    </ul>
                </li>
            </ul>
            </div>
            <!-- /.collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- /.navigation -->


    <!--
    ---- PAGE HEADER
    --->
    <div class="page-head">
        <div class="container">
            <div class="page-title">
                <h1>GEO-SECOURS</h1>
            </div>
            <!-- /.page-title -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.page-head -->


    <!--
    ---- PAGE CONTENT
    --->
    <div class="page-content">
        <div class="container">

            <div class="row">
                <div class="col-lg-12 margin-bottom-10">
                    <div class="portlet light">
                      <div class="row">
                        <div class="col-sm-8 margin-bottom-10">
                        <!-- /.portlet-title -->
                        <div class="portlet-body">
                          <!--<iframe width=100% height="500" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://www.openstreetmap.org/export/embed.html?bbox=8.5628,50.0781,8.8217,50.1877&amp;layer=mapnik" ></iframe>-->
                          <div id="map" style="width: 100%; height: 500px"></div>
                        </div>
                        <!-- /.portlet-body -->
                        </div>
                        <div class="col-sm-4 margin-bottom-10">
                          <div class="wrap">
                            <div class="wrap1">
                              <ul id="sortable-10">
                                <% @issues.each do |issue| %>
                                  <% if issue.issue_level.to_i == 1 %>
                                    <li class="default" style="background-color:#74ae32; color:white;">
                                  <% elsif issue.issue_level.to_i == 2 %>
                                    <li class="default" style="background-color:#f4963d; color:white;">
                                  <% elsif issue.issue_level.to_i == 3 %>
                                    <li class="default" style="background-color:#d43f31; color:white;">
                                  <% elsif issue.issue_level.to_i == 4 %>
                                    <li class="default" style="background-color:#a03439; color:white;">
                                  <% else %>
                                    <li class="default" style="background-color:#5b3b6a; color:white;">
                                  <% end %>
                                      <p>
                                      <% if issue.typeofperson.to_s == TypeofPerson::VICTIME.to_s %>
                                          Victime - <%= issue.nbr_victims %> victime(s) estimée(s)
                                      <% else %>
                                          Témoin - <%= issue.nbr_victims %> victime(s) estimée(s)
                                      <% end %>
                                      </p>
                                      <!--<br>-->
                                      <% if !issue.name.nil? and !issue.last_name.nil? %>
                                          <p> <%= issue.name %> <%= issue.last_name %></p>
                                      <% end %>
                                      <% if issue.phone != "" %>
                                        <p>Téléphone : <%= issue.phone %></p>
                                      <% end %>
                                      <%= link_to "+ d'infos", issue_path(issue)%>
                                      <br>
                                      <% if !issue.picture.url.nil? and issue.picture.url != "" %>
                                        <img src="<%= issue.picture %>" height="100px"></img>
                                      <% end %>
                                    </li>
                                <!--<li class="default" style="background-color: #1b6d85; color:white;"><p>+33123456789</p>Victime - inondation - 4/5</li>
                                <li class="default" style="background-color: red; color:white;"><p>+33123456789</p>Victime       - inondation - 4/5</li>-->
                                    <% end %>
                              </ul>
                            </div>
                          </div>
                        </div>
                    </div>
                    <!-- /.portlet -->
                  </div>
                </div>

                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.page-content -->


    <!--
    ---- FOOTER
    --->
    <div class="page-footer">
        <div class="container"> 2016 &copy; Urgence - DGGN</div>
    </div>
    <!-- /.page-footer -->


    <script>
      $(function() {
         $( "#sortable-10" ).sortable({
            start: function (event, ui) {
               $("span#result").html ($("span#result").html ()
                  + "<b>start</b><br>");
            },
            receive : function (event, ui)
            {
               $("span#result").html ($("span#result").html ()
                  + ", receive");
            },
            stop: function (event, ui) {
               $("span#result").html ($("span#result").html ()
                  + "<b>stop</b><br>");
            }
         });
         $( "#sortable-11" ).sortable({
            connectWith : "#sortable-10, #sortable-11"
         });
      });
   </script>

    <%= javascript_include_tag 'http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js' %>
    <%= javascript_include_tag 'leaflet.awesome-markers' %>


    <script>
      var map = L.map('map').setView([48.821189, 2.260321], 9);



      L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpandmbXliNDBjZWd2M2x6bDk3c2ZtOTkifQ._QA7i5Mpkd_m30IGElHziw', {
        maxZoom: 12,
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
        '<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
        'Imagery © <a href="http://mapbox.com">Mapbox</a>',
        id: 'mapbox.streets'
      }).addTo(map);

      <% @issues.each do |issue| %>
        L.marker([<%= issue.latitude %>, <%= issue.longitude %>], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor:
          <% if issue.issue_level.to_i == 1 %>
          'green',
          <% elsif issue.issue_level.to_i == 2 %>
          'orange',
          <% elsif issue.issue_level.to_i == 3 %>
          'red',
          <% elsif issue.issue_level.to_i == 4 %>
          'darkred',
          <% else %>
          'darkpurple',
          <% end %>
          iconColor: '#ff0000'}) }).addTo(map).bindPopup(
            <% if issue.typeofperson == TypeofPerson::VICTIME.to_s %>
                "<%# link_to "Victime", issue_path(issue)%><a href='/issues/<%=issue.id%>'>Victime</a>" + "<br>" + "<%= issue.phone %>" + "<br>Urgence <%= issue.issue_level %>/5"

              <% else %>
                "<%# link_to "Témoin", issue_path(issue)%><a href='/issues/<%=issue.id%>'>Victime</a>" + "<br>" + "<%= issue.phone %>" + "<br>Urgence <%= issue.issue_level %>/5"
              <% end %>
              );
      <% end %>
      /*L.marker([48.851189,2.27], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor: 'darkpurple', iconColor: '#ff0000'}) }).addTo(map).bindPopup("<b>Hello world!</b><br />I am a popup.");;
      L.marker([48.86189,2.27], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor: 'darkred', iconColor: '#ff0000'}) }).addTo(map).bindPopup("<b>Hello world!</b><br />I am a popup.");;
      L.marker([48.871189,2.27], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor: 'red', iconColor: '#ff0000'}) }).addTo(map).bindPopup("<b>Hello world!</b><br />I am a popup.");;
      L.marker([48.881189,2.27], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor: 'orange', iconColor: '#ff0000'}) }).addTo(map).bindPopup("<b>Hello world!</b><br />I am a popup.");;
      L.marker([48.891189,2.27], {icon: L.AwesomeMarkers.icon({icon: '', prefix: 'fa', markerColor: 'green', iconColor: '#ff0000'}) }).addTo(map).bindPopup("<b>Hello world!</b><br />I am a popup.");;*/
    </script>

</body>

webapp/app/views/layouts/_footer.html.erb
<!-- footer -->
<footer>
</footer>

webapp/app/views/layouts/_header.html.erb
<!-- header -->
<header>
</header>

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>
    <%= @title || "DGGN project" %> - DGGN project
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>


<section class="round">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
</section>

<%= render 'layouts/footer' %>

</body>
</html>

webapp/app/views/pages/home.html.erb
<%= javascript_include_tag 'usersinfo', 'data-turbolinks-track' => true %>


  <div>
    patientez nous vous localisons
  </div>

<script>
var ERROR;
function errorPosition(error){
    switch (error.code){
        case error.PERMISSION_DENIED:
            alert("Vous n'avez pas autorisé l'accés à la géolocalisation");
            break;
        case error.POSITION_UNAVAILABLE:
           ERROR = "Nous avons eu du mal à trouver votre position.. rafraichissez la page svp.";
           break;
        case error.TIMEOUT:
           ERROR = "La géolocalisation a mis trop de temps, rafraichissez la page svp.";
            break;
        default:
            break;
    }
};


var ip = null;

UserInfo.getInfo(function(data) {
          ip = data.ip_address;
          console.log(ip);
          if (navigator.geolocation)
          {
              navigator.geolocation.getCurrentPosition(successPosition, errorPosition, {enableHighAccuracy : true, timeout:30000, maximumAge:600000});

          }
          else
          {
             //  alert("fail");
          }
});

function successPosition(position) {

    var infopos = "Position déterminée :\n";
    infopos += "Latitude : "+position.coords.latitude +"\n";
    infopos += "Longitude: "+position.coords.longitude+"\n";
    infopos += "Altitude : "+position.coords.altitude +"\n";
    console.log(infopos);
    console.log(ip);
    $.ajax({
      type: "POST",
      url: "/ajax/set_ip_loc",
      data: '{'
       + '"ip" : "' + ip + '",'
       + '"lat" : "' + position.coords.latitude + '",'
       + '"pos" : "' + position.coords.longitude + '"'
       + '}'
     }).done(function() {
       window.location.replace('/issues/new');
     });
};
</script>

webapp/app/views/pages/remonte.html.erb
  <!-- Bootstrap Core CSS -->
  <!--  <link rel="stylesheet" href="css/bootstrap.min.css">-->
  <!-- Data Tables CSS -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.10/css/jquery.dataTables.min.css">
  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Custom CSS -->
  <!-- <link rel="stylesheet" href="css/stopcambriolage_catastrophe.css">-->

  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
  <% i = 0 %>
  <% if i == 0%>
      <%= stylesheet_link_tag    'stopcambriolage_catastrophe', media: 'all'%>
  <% end %>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->


<body>

    <!--
    ---- NAVIGATION BAR
    --->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/issues">
                  <%= image_tag("gendarmerie_logo.svg", height: '30') %>
                </a>
            </div>
            <!-- /.navbar-header -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/issues">VSU</a>
                    </li>
                    <li class="active">
                        <a href="/pages/remonte">Signalements</a>
                    </li>
                  <!--<li>
                      <a href="/pages/info">Statistiques</a>
                  </li>-->
                    <li>
                        <a href="/pages/reseaux">Réseaux Sociaux</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        sicard_f&nbsp;
                        <i class="fa fa-chevron-down"></i>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-refresh" style="margin-right:10px"></i>Mode Catastrophe</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-sign-out" style="margin-right:8px"></i>Déconnexion</a>
                        </li>
                    </ul>
                </li>
            </ul>
            </div>
            <!-- /.collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- /.navigation -->


    <!--
    ---- PAGE HEADER
    --->
    <div class="page-head">
        <div class="container">
            <div class="page-title">
                <h1>Signalements <small>& bilan</small></h1>
            </div>
            <!-- /.page-title -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.page-head -->


    <!--
    ---- PAGE CONTENT
    --->
    <div class="page-content">
        <div class="container">






         <div class="row">
                <div class="col-lg-12 margin-bottom-10">
                    <div class="portlet light">
                        <div class="portlet-title">
                            <div class="caption">Push</div>
                        </div>
                        <div class="portlet-body">
                            <table id="push-table" class="display" cellspacing="0" width="100%">

                                <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Type</th>
                                        <th>Nombre Victime</th>
                                        <th>Importance</th>
                                        <th>Téléphone</th>
                                        <th>IP</th>
                                    </tr>
                                </thead>
                                <tbody>

                                <% @issues.each do |issue| %>
                                    <tr>
                                    <td><%= distance_of_time_in_words_to_now(issue.updated_at) %></td>
                                    <% if issue.typeofperson.to_s == TypeofPerson::VICTIME.to_s %>
                                       <!-- <td><a href="/issues/show/<%= issue.id %>">Témoin</a></td>-->
                                          <td><%= link_to "Victime", issue_path(issue)%> </td>
                                    <% else %>
                                          <td><%= link_to "Témoin", issue_path(issue)%> </td>
                                    <% end %>
                                    <td><%= issue.nbr_victims %></td>
                                    <td><%= issue.issue_level %></td>
                                    <td><%= issue.phone %></td>
                                    <td><%= issue.ip %></td>
                                      </tr>
                                    <!--<li class="default" style="background-color: #1b6d85; color:white;"><p>+33123456789</p>Victime - inondation - 4/5</li>
                                    <li class="default" style="background-color: red; color:white;"><p>+33123456789</p>Victime       - inondation - 4/5</li>-->
                                <% end %>




                                  <!--  <tr>
                                        <td><a href="/dashboard/push/{{ i.pk }}/" >LO2</a></td>
                                        <td><a href="/dashboard/department/{{ i.department.zip }}/" >LO3</a></td>
                                        <td>pr</td>
                                    </tr>-->

                                </tbody>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </div>
    <!-- /.page-content -->


    <!--
    ---- FOOTER
    --->
    <div class="page-footer">
        <div class="container"> 2016 &copy; Urgence - DGGN</div>
    </div>
    <!-- /.page-footer -->

    <!-- Data Tables JavaScript -->
    <script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>
    <!-- Settings Data Tables JavaScript -->
    <script>
        $(document).ready(function() {
            $('#news-table').DataTable( {
                "scrollX": true,
                "scrollXollapse": true,
                "language": { "lengthMenu": "Afficher _MENU_",
                              "oPaginate": { "sFirst": "Suivant", // This is the link to the first page
                                             "sPrevious": "Précédent", // This is the link to the previous page
                                             "sNext": "Suivant", // This is the link to the next page
                                             "sLast": "Précédent" }
                            },
                "info": false,
                "bFilter": false,
            } );
        } );

        $(document).ready(function() {
            $('#push-table').DataTable( {
                "scrollX": true,
                "scrollXollapse": true,
                "language": { "lengthMenu": "Afficher _MENU_",
                              "oPaginate": { "sFirst": "Suivant", // This is the link to the first page
                                             "sPrevious": "Précédent", // This is the link to the previous page
                                             "sNext": "Suivant", // This is the link to the next page
                                             "sLast": "Précédent" }
                            },
                "info": false,
                "bFilter": false,
            } );
        } );
    </script>
</body>


</html>